manifest:
  remotes:
    - name: JsmnRepo
      url-base: https://github.com/zserge
    - name: LairdCP
      url-base: https://github.com/LairdCP

  # Please add items below based on alphabetical order.
  # These dependencies may need updating if new features are added to the firmware.
  projects:
    - name: jsmn
      path: modules/jsmn
      revision: 7b6858a5855299d173c5ab2b46e611bf9961cbef
      remote: JsmnRepo
    - name: Pinnacle_100_oob_demo
      path: oob_demo
      revision: v2.1.0
      remote: LairdCP
    - name: zephyr
      west-commands: scripts/west-commands.yml
      revision: hl7800-v2.0.0
      remote: LairdCP
      import: true
    - name: zephyr_framework
      path: modules/framework
      revision: fd546c5341075a172f243aaefad23c465fdf2c79
      remote: LairdCP
    - name: zephyr-hal-lairdconnectivity
      path: zephyr/ext/hal/lairdconnectivity
      revision: f2e46c9ad8da72868d48b1eb2daf623c97817b42
      remote: LairdCP
    - name: zephyr_boards
      path: zephyr/boards/arm
      revision: 958483b12e5868b04409d765af582613a499f20d
      remote: LairdCP
    - name: zephyr_lib
      path: modules/zephyr_lib
      revision: a70f04f602b5a245e14eb9c83d73739036b2ddd3
      remote: LairdCP

  self:
    path: manifest_repo
